version: "3"


services:
  rabbit-mq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "8080:15672"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: RSS_News
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5