# Generated by Django 4.1.6 on 2023-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='source_link',
            field=models.URLField(max_length=300),
        ),
    ]
